ubiquitin = (
    'MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYN'
    'IQKESTLHLVLRLRGG'
)

gfp = (
    'MVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQ'
    'CFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGH'
    'KLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSK'
    'DPNEKRDHMVLLEFVTAAGITLGMDELYK'
)

mcherry = (
    'MVSKGEEDNMAIIKEFMRFKVHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSPQF'
    'MYGSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLRGTNFPSDGPV'
    'MQKKTMGWEASSERMYPEDGALKGEIKQRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNVNIKLDITSHN'
    'EDYTIVEQYERAEGRHSTGGMDELYK'
)

firefly_luciferase = (
    'MEDAKNIKKGPAPFYPLEDGTAGEQLHKAMKRYALVPGTIAFTDAHIEVDITYAEYFEMSVRLAEAMKRY'
    'GLNTNHRIVVCSENSLQFFMPVLGALFIGVAVAPANDIYNERELLNSMGISQPTVVFVSKKGLQKILNVQ'
    'KKLPIIQKIIIMDSKTDYQGFQSMYTFVTSHLPPGFNEYDFVPESFDRDKTIALIMNSSGSTGLPKGVAL'
    'PHRTACVRFSHARDPIFGNQIIPDTAILSVVPFHHGFGMFTTLGYLICGFRVVLMYRFEEELFLRSLQDY'
    'KIQSALLVPTLFSFFAKSTLIDKYDLSNLHEIASGGAPLSKEVGEAVAKRFHLPGIRQGYGLTETTSAIL'
    'ITPEGDDKPGAVGKVVPFFEAKVVDLDTGKTLGVNQRGELCVRGPMIMSGYVNNPEATNALIDKDGWLHS'
    'GDIAYWDEDEHFFIVDRLKSLIKYKGYQVAPAELESILLQHPNIFDAGVAGLPDDDAGELPAAVVVLEHG'
    'KTMTEKEIVDYVASQVTTAKKLRGGVVFVDEVPKGLTGKLDARKIREILIKAKKGGKIAV'
)

collagen = (
    'PPGPPGPPGITGARGLAGPPGPPGPPGPPG'
)

hard = (
    'GAPGAPGTPGPQGLLGAPGFPGLKGEPGDIKGAPGFPGPKGPRGPPGPQGVRGEPGQAGVMGFPGERGVP'
    'GPPGPPGPPGPPGLAGPPGPMGPPGPQGAPGPKGDTGAPGPAGPAGPRGEPGPPGPPGPPGPPGPPGPPG'
    'PPGPPGPPGPPGLGGN'
)

also_hard = (
    'VPGPPGPPGPPGPP'
)

elastin = (
    'MRSLTAAARRPEVLLLLLCILQPSQPGGVPGAVPGGVPGGVFFPGAGLGGLGVGGLGPGVKPAKPGVGGL'
    'VGPGLGAEGSALPGAFPGGFFGAGGGAAGAAAAYKAAAKAGAAGLGVGGIGGVGGLGVSTGAVVPQLGAG'
    'VGAGVKPGKVPGVGLPGVYPGGVLPGAGARFPGIGVLPGVPTGAGVKPKAQVGAGAFAGIPGVGPFGGQQ'
    'PGLPLGYPIKAPKLPAGYGLPYKTGKLPYGFGPGGVAGSAGKAGYPTGTGVGPQAAAAAAKAAAKLGAGG'
    'AGVLPGVGVGGPGIPGAPGAIPGIGGIAGVGAPDAAAAAAAAAKAAKFGAAGGLPGVGVPGVGVPGVGVP'
    'GVGVPGVGVPGVGVPGVGVPGVGVPGVGVPGVGVPGVGVPGALSPAATAKAAAKAAKFGARGAVGIGGIP'
    'TFGLGPGGFPGIGDAAAAPAAAAAKAAKIGAGGVGALGGVVPGAPGAIPGLPGVGGVPGVGIPAAAAAKA'
    'AAKAAQFGLGPGVGVAPGVGVVPGVGVVPGVGVAPGIGLGPGGVIGAGVPAAAKSAAKAAAKAQFRAAAG'
    'LPAGVPGLGVGAGVPGLGVGAGVPGLGVGAGVPGPGAVPGTLAAAKAAKFGPGGVGALGGVGDLGGAGIP'
    'GGVAGVVPAAAAAAKAAAKAAQFGLGGVGGLGVGGLGAVPGAVGLGGVSPAAAAKAAKFGAAGLGGVLGA'
    'GQPFPIGGGAGGLGVGGKPPKPFGGALGALGFPGGACLGKSCGRKRK'
)

caplacizumab = (
    'MEVQLVESGGGLVQPGGSLRLSCAASGRTFSYNPMGWFRQAPGKGRELVAAISRTGGSTYYPDSVEGRFT'
    'ISRDNAKRMVYLQMNSLRAEDTAVYYCAAAGVRAEDGRVRTLPSEYTFWGQGTQVTVSSLEHHHHHH'
)

nbalfa = (
    'SGEVQLQESGGGLVQPGGSLRLSCTASGVTISALNAMAMGWYRQAPGERRVMVAAVSERGNAMYRESVQG'
    'RFTVTRDFTNKMVSLQMDNLKPEDTAVYYCHVLEDRVDSFHDYWGQGTQVTVSS'
)

pdb_8qf3 = (
    'GSEVQLLESGGGLVQAGDSLRLSCAASGRTFSAYAMGWFRQAPGKEREFVAAISWSGNSTYYADSVKGRF'
    'TISRDNAKNTVYLQMNSLKPEDTAIYYCAARKPMYRVDISKGQNYDYWGQGTQVTVSS'
)

spcas9 = (
    'MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEATRLKRTARR'
    'RYTRRKNRICYLQEIFSNEMAKVDDSFFHRLEESFLVEEDKKHERHPIFGNIVDEVAYHEKYPTIYHLRK'
    'KLVDSTDKADLRLIYLALAHMIKFRGHFLIEGDLNPDNSDVDKLFIQLVQTYNQLFEENPINASGVDAKA'
    'ILSARLSKSRRLENLIAQLPGEKKNGLFGNLIALSLGLTPNFKSNFDLAEDAKLQLSKDTYDDDLDNLLA'
    'QIGDQYADLFLAAKNLSDAILLSDILRVNTEITKAPLSASMIKRYDEHHQDLTLLKALVRQQLPEKYKEI'
    'FFDQSKNGYAGYIDGGASQEEFYKFIKPILEKMDGTEELLVKLNREDLLRKQRTFDNGSIPHQIHLGELH'
    'AILRRQEDFYPFLKDNREKIEKILTFRIPYYVGPLARGNSRFAWMTRKSEETITPWNFEEVVDKGASAQS'
    'FIERMTNFDKNLPNEKVLPKHSLLYEYFTVYNELTKVKYVTEGMRKPAFLSGEQKKAIVDLLFKTNRKVT'
    'VKQLKEDYFKKIECFDSVEISGVEDRFNASLGTYHDLLKIIKDKDFLDNEENEDILEDIVLTLTLFEDRE'
    'MIEERLKTYAHLFDDKVMKQLKRRRYTGWGRLSRKLINGIRDKQSGKTILDFLKSDGFANRNFMQLIHDD'
    'SLTFKEDIQKAQVSGQGDSLHEHIANLAGSPAIKKGILQTVKVVDELVKVMGRHKPENIVIEMARENQTT'
    'QKGQKNSRERMKRIEEGIKELGSQILKEHPVENTQLQNEKLYLYYLQNGRDMYVDQELDINRLSDYDVDH'
    'IVPQSFLKDDSIDNKVLTRSDKNRGKSDNVPSEEVVKKMKNYWRQLLNAKLITQRKFDNLTKAERGGLSE'
    'LDKAGFIKRQLVETRQITKHVAQILDSRMNTKYDENDKLIREVKVITLKSKLVSDFRKDFQFYKVREINN'
    'YHHAHDAYLNAVVGTALIKKYPKLESEFVYGDYKVYDVRKMIAKSEQEIGKATAKYFFYSNIMNFFKTEI'
    'TLANGEIRKRPLIETNGETGEIVWDKGRDFATVRKVLSMPQVNIVKKTEVQTGGFSKESILPKRNSDKLI'
    'ARKKDWDPKKYGGFDSPTVAYSVLVVAKVEKGKSKKLKSVKELLGITIMERSSFEKNPIDFLEAKGYKEV'
    'KKDLIIKLPKYSLFELENGRKRMLASAGELQKGNELALPSKYVNFLYLASHYEKLKGSPEDNEQKQLFVE'
    'QHKHYLDEIIEQISEFSKRVILADANLDKVLSAYNKHRDKPIREQAENIIHLFTLTNLGAPAAFKYFDTT'
    'IDRKRYTSTKEVLDATLIHQSITGLYETRIDLSQLGGD'
)


NORMAL_PROTEINS = {
    'ubiquitin': ubiquitin,
    'gfp': gfp,
    'mcherry': mcherry,
    'firefly_luciferase': firefly_luciferase,
}

DIFFICULT_PROTEINS = {
    'collagen': collagen,
    'hard': hard,
    'also_hard': also_hard,
    'elastin': elastin,
}

ANTIBODIES = {
    'caplacizumab': caplacizumab,
    'nbalfa': nbalfa,
    'pdb_8qf3': pdb_8qf3,
}

LARGE_PROTEINS = {
    'spcas9': spcas9,
}
